# Site
title: 王子亭的博客
subtitle:
description:
author: 王子亭
email: jysperm@gmail.com
language: zh-CN

# URL
url: https://jysperm.me
root: /
permalink: :year/:month/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tag
archive_dir: ''
category_dir: ''
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month-:day#:title.md
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  tab_replace:

# Category & Tag
tag_map:
  Atom: atom
  C++: cpp
  C++讲稿: cpp-ppt
  Docker: docker
  Golang: golang
  Hexo: hexo
  HTML: html
  JavaScript: javascript
  LeanCloud: leancloud
  LightPHP: lightphp
  Linux: linux
  MongoDB: mongodb
  Node.js: nodejs
  PHP: php
  Qt: qt
  RootPanel: rootpanel
  RP主机: rpvhost
  SICP: sicp
  Web: web
  中医: traditional-medicine
  互联网: internet
  互联网资讯: news
  价值观: values
  作品: works
  信息安全: information-security
  冷知识: cold-knowledge
  区块链: blockchain
  单元测试: unit-test
  博客: blog
  去中心化: decentralization
  哆啦A梦: doraemon
  学校周记: school-weekly
  学校考试: exam
  密码学: cryptography
  小璐: xiaolu
  年度小结: summary-of-year
  年度技术小结: programming-of-year
  彩排: caipai
  徐雪丽: xuxueli
  总结: summary
  技术: technology
  教程: tutorials
  教育: education
  服务器端: server-side
  比特币: bitcoin
  游戏: gaming
  物理: physical
  生活: live
  生活记录: live
  电影: movie
  科普: science
  笔记: reading-notes
  精子的故事: story-of-sperm
  编程: programming
  编程语言: programming-language
  蛋黄: yellow-bud
  计算机科学: computer-science
  计算机网络: network
  读书: reading
  购物: shopping
  软件工程: software-engineering
  随笔: note
  零毫秒: zeroms
  黑客: hacker
  网络: networking
  硬件: hardware
  开源: opensource

# Date / Time format
date_format: YYYY M 月 D 日
time_format: H:mm:ss

# Pagination
per_page: 3
pagination_dir: page

# Extensions
theme: simpleblock

# Deployment
deploy:
  type: rsync
  host: ap-home
  user: www-data
  root: /home/www-data/blog

# Hexo RSS
feed:
  type: atom
  path: atom.xml
  limit: 30

# Personal extends
cdn_prefix: '/pictures/'
