# Site
title: 王子亭的博客
subtitle:
description:
author: 王子亭
email: jysperm@gmail.com
language: zh-CN

# URL
url: https://jysperm.me
root: /
permalink: :year/:month/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tag
archive_dir: ''
category_dir: ''
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month-:day#:title.md
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  tab_replace:

# Category & Tag
tag_map:
  Atom: atom
  C++: cpp
  C++讲稿: cpp-ppt
  Golang: golang
  HTML: html
  Hexo: hexo
  JavaScript: javascript
  LightPHP: lightphp
  Linux: linux
  MongoDB: mongodb
  PHP: php
  RP主机: rpvhost
  RootPanel: rootpanel
  SICP: sicp

  信息安全: information-security
  软件工程: software-engineering
  Node.js: nodejs
  技术: technology
  计算机网络: network
  互联网: internet
  笔记: reading-notes
  价值观: values
  教程: tutorials
  读书: reading
  小璐: xiaolu
  总结: summary
  教育: education
  作品: works
  随笔: note
  单元测试: unit-test
  生活: live
  互联网资讯: news
  购物: shopping
  生活记录: live
  物理: physical
  计算机科学: computer-science
  电影: movie
  博客: blog
  学校考试: exam
  黑客: hacker
  零毫秒: zeroms
  学校周记: school-weekly
  密码学: cryptography
  比特币: bitcoin
  徐雪丽: xuxueli
  冷知识: cold-knowledge
  精子的故事: story-of-sperm
  科普: science
  精子的故事: story-of-sperm
  Qt: qt
  年度小结: summary-of-year
  哆啦A梦: doraemon

# Date / Time format
date_format: YYYY M 月 D 日
time_format: H:mm:ss

# Pagination
per_page: 3
pagination_dir: page

# Extensions
theme: simpleblock

# Deployment
deploy:
  type: rsync
  host: spawn.rpvhost.net
  user: docker
  root: /home/docker/sites/blog

feed:
  type: atom
  path: atom.xml
  limit: 30
